### ISSUE TITLE
This isn't the sql_compiler, it's index_util.

### ISSUE THREAD

**Issue by calroc** [cmungall/sql_compiler-OLD#1]
It seems there was a mix up, this repo has the wrong code, or title.

**Comment by cmungall** [comment]
thanks. Haven't had a chance to rectify..

**Comment by cmungall** [comment]
in the interim you can get my mods to the original draxler sql_compiler here: https://github.com/cmungall/blipkit/blob/master/packages/sql/sql_compiler.pro

**Comment by cmungall** [comment]
there is something very odd with the giit history of this repo, I will move and put another in its place
